/**
 * Resend Email Integration
 * Used for transactional emails (report delivery, etc)
 */

import { Resend } from 'resend';

let resendClient: Resend | null = null;

function getResendClient(): Resend | null {
  if (!process.env.RESEND_API_KEY) {
    console.log('RESEND_API_KEY not configured');
    return null;
  }
  if (!resendClient) {
    resendClient = new Resend(process.env.RESEND_API_KEY);
  }
  return resendClient;
}

const FROM_EMAIL = process.env.EMAIL_FROM || 'reports@timkilroy.com';

interface SendEmailParams {
  to: string;
  subject: string;
  html?: string;
  text?: string;
}

export async function sendEmail(params: SendEmailParams): Promise<{ success: boolean; error?: string }> {
  const resend = getResendClient();
  if (!resend) {
    return { success: false, error: 'Resend not configured' };
  }

  try {
    const { error } = await resend.emails.send({
      from: `SalesOS <${FROM_EMAIL}>`,
      to: params.to,
      subject: params.subject,
      html: params.html,
      text: params.text,
    });

    if (error) {
      console.error('Resend email error:', error);
      return { success: false, error: error.message };
    }

    return { success: true };
  } catch (err) {
    console.error('Resend email exception:', err);
    return { success: false, error: err instanceof Error ? err.message : 'Unknown error' };
  }
}

/**
 * Send Discovery Lab report email
 */
export async function sendDiscoveryLabReportEmail(
  to: string,
  userName: string,
  targetCompany: string,
  targetContact: string | undefined,
  reportMarkdown: string,
  reportUrl?: string
): Promise<{ success: boolean; error?: string }> {
  // Convert markdown to simple HTML (basic conversion)
  const htmlContent = markdownToHtml(reportMarkdown);

  const subject = `Your Discovery Lab Playbook for ${targetCompany}${targetContact ? ` (${targetContact})` : ''}`;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1, h2, h3, h4 { color: #E51B23; margin-top: 24px; }
    h1 { font-size: 28px; border-bottom: 2px solid #E51B23; padding-bottom: 8px; }
    h2 { font-size: 22px; }
    h3 { font-size: 18px; color: #333; }
    ul, ol { margin: 12px 0; padding-left: 24px; }
    li { margin: 8px 0; }
    strong { color: #E51B23; }
    blockquote { border-left: 3px solid #FFDE59; padding-left: 16px; margin: 16px 0; color: #666; }
    .header { background: #000; color: #fff; padding: 24px; margin: -20px -20px 24px -20px; }
    .header h1 { color: #FFDE59; border: none; margin: 0; }
    .header p { color: #ccc; margin: 8px 0 0 0; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; color: #666; font-size: 14px; }
    .cta { background: #E51B23; color: #fff; padding: 12px 24px; text-decoration: none; display: inline-block; margin: 16px 0; font-weight: bold; }
    .cta:hover { background: #FFDE59; color: #000; }
  </style>
</head>
<body>
  <div class="header">
    <h1>DISCOVERY LAB PRO</h1>
    <p>Your playbook for ${targetCompany}</p>
  </div>

  <p>Hi ${userName || 'there'},</p>

  <p>Your Discovery Lab Pro playbook is ready. Here's everything you need for your call with ${targetContact || targetCompany}.</p>

  ${reportUrl ? `<a href="${reportUrl}" class="cta">VIEW ONLINE</a>` : ''}

  <hr style="margin: 24px 0; border: none; border-top: 1px solid #ddd;">

  ${htmlContent}

  <div class="footer">
    <p>Generated by <strong>SalesOS Discovery Lab Pro</strong></p>
    <p>Questions? Reply to this email or reach out to tim@timkilroy.com</p>
  </div>
</body>
</html>
  `.trim();

  return sendEmail({
    to,
    subject,
    html,
    text: `Discovery Lab Pro Playbook for ${targetCompany}\n\n${reportMarkdown}`,
  });
}

/**
 * Basic markdown to HTML conversion
 */
function markdownToHtml(markdown: string): string {
  return markdown
    // Headers
    .replace(/^#### (.*)$/gm, '<h4>$1</h4>')
    .replace(/^### (.*)$/gm, '<h3>$1</h3>')
    .replace(/^## (.*)$/gm, '<h2>$1</h2>')
    .replace(/^# (.*)$/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    // Unordered lists
    .replace(/^- (.*)$/gm, '<li>$1</li>')
    // Ordered lists
    .replace(/^\d+\. (.*)$/gm, '<li>$1</li>')
    // Blockquotes
    .replace(/^> (.*)$/gm, '<blockquote>$1</blockquote>')
    // Line breaks
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>')
    // Wrap in paragraphs
    .replace(/^(.*)$/gm, (match) => {
      if (match.startsWith('<h') || match.startsWith('<li') || match.startsWith('<blockquote') || match.startsWith('</')) {
        return match;
      }
      return `<p>${match}</p>`;
    })
    // Clean up empty paragraphs
    .replace(/<p><\/p>/g, '')
    .replace(/<p><br><\/p>/g, '')
    // Wrap lists
    .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>');
}
