-- ============================================
-- WTF Growth OS - Coaching System Schema
-- Weekly/Monthly/Quarterly Coaching Reports
-- ============================================
-- NOTE: This documents the EXISTING coaching_reports table.
-- The table already exists in Supabase with org_id references.
-- This file is for reference only - DO NOT RUN if table exists.

-- ============================================
-- COACHING REPORTS (Weekly/Monthly/Quarterly)
-- ============================================
-- Existing table structure (for reference):
--
-- CREATE TABLE IF NOT EXISTS coaching_reports (
--   id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   user_id             uuid REFERENCES users(id) ON DELETE CASCADE,
--   org_id              uuid,  -- References organization
--
--   -- Report Type and Period
--   report_type         text NOT NULL CHECK (report_type IN ('weekly', 'monthly', 'quarterly')),
--   period_start        date NOT NULL,
--   period_end          date NOT NULL,
--
--   -- Aggregate Scores (averages for period)
--   scores_aggregate    jsonb DEFAULT '{}',
--
--   -- Report Content (separate columns)
--   key_wins            jsonb DEFAULT '[]',      -- What's working well
--   areas_to_improve    jsonb DEFAULT '[]',      -- Areas needing work
--   action_items        jsonb DEFAULT '[]',      -- Specific actions to take
--   pattern_breakdown   jsonb DEFAULT '{}',      -- Pattern analysis
--   trend_analysis      jsonb DEFAULT '{}',      -- Trends over time
--   executive_summary   text,                    -- High-level summary
--
--   -- Email Tracking
--   email_sent_at       timestamptz,
--   email_opened_at     timestamptz,
--
--   -- Metadata
--   created_at          timestamptz DEFAULT now()
-- );

-- If you need to add the unique constraint (if not exists):
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_coaching_reports_unique_period
--   ON coaching_reports(user_id, report_type, period_start, period_end);

-- ============================================
-- ROW LEVEL SECURITY (if not already enabled)
-- ============================================
-- ALTER TABLE coaching_reports ENABLE ROW LEVEL SECURITY;

-- Users can read their own coaching reports
-- CREATE POLICY "Users read own coaching reports" ON coaching_reports
--   FOR SELECT USING (user_id = auth.uid());

-- Service role can insert/update coaching reports (for cron jobs)
-- CREATE POLICY "Service role insert coaching reports" ON coaching_reports
--   FOR INSERT WITH CHECK (true);

-- CREATE POLICY "Service role update coaching reports" ON coaching_reports
--   FOR UPDATE USING (true);
