-- Create discovery_briefs table for Discovery Lab feature
-- This table stores pre-call intelligence briefs generated by Discovery Lab

CREATE TABLE IF NOT EXISTS discovery_briefs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  agency_id UUID NOT NULL REFERENCES agencies(id) ON DELETE CASCADE,
  version VARCHAR(20) NOT NULL DEFAULT 'lite',

  -- Input fields (Lite)
  what_you_sell TEXT NOT NULL,
  market_concerns TEXT,
  target_company VARCHAR(255) NOT NULL,
  target_contact_name VARCHAR(255),
  target_contact_title VARCHAR(255),

  -- Input fields (Pro only)
  target_company_url VARCHAR(500),
  target_linkedin_url VARCHAR(500),
  product_strengths TEXT,
  deal_context JSONB DEFAULT '{}',

  -- Output fields (Lite)
  markdown_response TEXT,
  questions JSONB DEFAULT '[]',
  meeting_frames JSONB DEFAULT '[]',

  -- Output fields (Pro only)
  market_intel JSONB DEFAULT '{}',
  company_intel JSONB DEFAULT '{}',
  prospect_intel JSONB DEFAULT '{}',
  opening_script TEXT,
  authority_questions JSONB DEFAULT '[]',
  depth_questions JSONB DEFAULT '[]',
  guidance_questions JSONB DEFAULT '[]',
  permission_gates JSONB DEFAULT '[]',
  google_radar JSONB DEFAULT '[]',
  meeting_agenda TEXT,
  decision_tree JSONB DEFAULT '{}',

  -- Metadata
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_agency_id ON discovery_briefs(agency_id);
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_user_id ON discovery_briefs(user_id);
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_created_at ON discovery_briefs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_target_company ON discovery_briefs(target_company);

-- Enable RLS
ALTER TABLE discovery_briefs ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their agency's discovery briefs"
  ON discovery_briefs FOR SELECT
  USING (
    agency_id IN (
      SELECT agency_id FROM user_agency_assignments
      WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert discovery briefs for their agency"
  ON discovery_briefs FOR INSERT
  WITH CHECK (
    agency_id IN (
      SELECT agency_id FROM user_agency_assignments
      WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update their agency's discovery briefs"
  ON discovery_briefs FOR UPDATE
  USING (
    agency_id IN (
      SELECT agency_id FROM user_agency_assignments
      WHERE user_id = auth.uid()
    )
  );

-- Service role bypass for API operations
CREATE POLICY "Service role can do anything"
  ON discovery_briefs FOR ALL
  USING (auth.role() = 'service_role');

-- Add comment to table
COMMENT ON TABLE discovery_briefs IS 'Stores pre-call intelligence briefs generated by Discovery Lab (Lite and Pro)';
