-- Create discovery_briefs table for Discovery Lab feature
-- This table stores pre-call intelligence briefs generated by Discovery Lab
-- STANDALONE VERSION: No foreign key constraints (run full schema.sql later for FK support)

CREATE TABLE IF NOT EXISTS discovery_briefs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- User/Agency references (no FK constraints for standalone operation)
  user_id UUID,
  agency_id UUID,

  -- Lead info (for users without accounts)
  lead_email TEXT,
  lead_name TEXT,
  lead_company TEXT,

  version VARCHAR(20) NOT NULL DEFAULT 'lite',

  -- Input fields (Lite)
  what_you_sell TEXT NOT NULL,
  market_concerns TEXT,
  target_company VARCHAR(255) NOT NULL,
  target_contact_name VARCHAR(255),
  target_contact_title VARCHAR(255),

  -- Input fields (Pro only)
  target_company_url VARCHAR(500),
  target_linkedin_url VARCHAR(500),
  product_strengths TEXT,
  deal_context JSONB DEFAULT '{}',

  -- Output fields (Lite)
  markdown_response TEXT,
  questions JSONB DEFAULT '[]',
  meeting_frames JSONB DEFAULT '[]',

  -- Output fields (Pro only)
  market_intel JSONB DEFAULT '{}',
  company_intel JSONB DEFAULT '{}',
  prospect_intel JSONB DEFAULT '{}',
  opening_script TEXT,
  authority_questions JSONB DEFAULT '[]',
  depth_questions JSONB DEFAULT '[]',
  guidance_questions JSONB DEFAULT '[]',
  permission_gates JSONB DEFAULT '[]',
  google_radar JSONB DEFAULT '[]',
  meeting_agenda TEXT,
  decision_tree JSONB DEFAULT '{}',

  -- Metadata
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_agency_id ON discovery_briefs(agency_id);
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_user_id ON discovery_briefs(user_id);
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_lead_email ON discovery_briefs(lead_email);
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_created_at ON discovery_briefs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_discovery_briefs_target_company ON discovery_briefs(target_company);

-- Enable RLS
ALTER TABLE discovery_briefs ENABLE ROW LEVEL SECURITY;

-- Service role bypass for API operations (lead magnet flow)
CREATE POLICY "Service role can do anything"
  ON discovery_briefs FOR ALL
  USING (auth.role() = 'service_role');

-- Users can view their own briefs by email
CREATE POLICY "Users can view their own briefs by email"
  ON discovery_briefs FOR SELECT
  USING (lead_email = auth.jwt()->>'email');

-- Add comment to table
COMMENT ON TABLE discovery_briefs IS 'Stores pre-call intelligence briefs generated by Discovery Lab (Lite and Pro) - Standalone version';
